WITH table_1 AS (
  SELECT
    customer_id,
    total - 0.8 AS _expr_0,
    total
  FROM
    invoices
),
table_2 AS (
  SELECT
    SUM(_expr_0) AS sum_income,
    customer_id
  FROM
    table_1
  WHERE
    _expr_0 > 1
  GROUP BY
    customer_id
  ORDER BY
    sum_income DESC
  LIMIT
    10
)
SELECT
  c.customer_id,
  c.last_name || ', ' || c.first_name AS name,
  table_2.sum_income
FROM
  table_2
  JOIN customers AS c ON table_2.customer_id = c.customer_id

-- Generated by PRQL compiler version:0.5.0 target:sql.sqlite (https://prql-lang.org)
