WITH table_0 AS (
  SELECT
    *
  from
    read_parquet(
      "s3://gbif-open-data-us-east-1/occurrence/2023-03-01/occurrence.parquet/000000"
    )
)
SELECT
  genus,
  species,
  COUNT(*) AS total
FROM
  table_0
WHERE
  genus = 'Anas'
GROUP BY
  genus,
  species
ORDER BY
  total DESC
LIMIT
  10

-- Generated by PRQL compiler version:0.9.1 target:sql.duckdb (https://prql-lang.org)
