WITH table_1 AS (
  SELECT
    STRFTIME('%Y-%m', i.invoice_date) AS month,
    STRFTIME('%Y-%m-%d', i.invoice_date) AS day,
    COUNT(DISTINCT i.invoice_id) AS num_orders,
    SUM(ii.quantity) AS num_tracks,
    SUM(ii.unit_price * ii.quantity) AS total_price
  FROM
    invoices AS i
    JOIN invoice_items AS ii ON i.invoice_id
  GROUP BY
    STRFTIME('%Y-%m', i.invoice_date),
    STRFTIME('%Y-%m-%d', i.invoice_date)
)
SELECT
  month,
  day,
  num_orders,
  num_tracks,
  total_price,
  SUM(num_tracks) OVER (
    PARTITION BY month
    ORDER BY
      day ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
  ) AS running_total_num_tracks,
  LAG(num_tracks, 7) OVER (
    ORDER BY
      day ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING
  ) AS num_tracks_last_week
FROM
  table_1
ORDER BY
  day

-- Generated by PRQL compiler version 0.4.0 (https://prql-lang.org)
