SELECT
  employee_id,
  first_name,
  last_name,
  birth_date,
  (DATE '2023-02-12' - birth_date) / 365 AS age
FROM
  employees

-- Generated by PRQL compiler version:0.5.0 target:sql.duckdb (https://prql-lang.org)
