SELECT
  employee_id,
  first_name,
  last_name,
  birth_date,
  ((DATE '2023-10-14' - birth_date) / 365) AS age
FROM
  employees

-- Generated by PRQL compiler version:0.9.1 target:sql.duckdb (https://prql-lang.org)
