WITH table_1 AS (
  SELECT
    *,
    ROW_NUMBER() OVER (
      PARTITION BY title
      ORDER BY
        hire_date
    ) AS _expr_0
  FROM
    employees
)
SELECT
  * EXCLUDE (_expr_0)
FROM
  table_1
WHERE
  _expr_0 <= 1

-- Generated by PRQL compiler version:0.5.0 target:sql.duckdb (https://prql-lang.org)
